name: Deploy App

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous redudant build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - name: install dependencies
        run: npm install  --no-audit --no-fund
      - name: output
        run: echo "cache install npm"

  linter:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - name: install dependencies
        run: npm install  --no-audit --no-fund
      - name: Check linter
        run: npm run lint
      - run: ls -l

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - name: install dependencies
        run: npm install  --no-audit --no-fund
      - name: Build
        run: npm run build
      - name: create build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-prod
          path: build

  testing:
    needs: [linter, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - name: install dependencies
        run: npm install  --no-audit --no-fund
      - name: pull build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-prod
          path: build
      - name: Unit test
        run: npm run test

  testinge2e:
    needs: [linter, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - name: install dependencies
        run: npm install  --no-audit --no-fund
      - name: pull build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-prod
          path: build
      - name: E2E test
        run: echo "testing end to end..."
    #    uses: cypress-io/github-action@v2
    #    with:
    #      command: npm run test:e2e
    #      start:
    #      wait-on: localhost

  deploy:
    needs: [testing, testinge2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy App to Heroku
        if: ${{github.event_name=='push'}}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_APP_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_APP_ACCOUNT}}
